### ISSUE TITLE
Error while deploying

### ISSUE THREAD

**Issue by arrubiu** [TryGhost/action-deploy-theme#12]
I'm trying this tool to deploy my theme on a self-hosted (docker) ghost 3 installation.

First question: I'm pushing code (files!) of my theme. Is it right?

This is my yaml:

```
name: Deploy Theme
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1.2.0
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: cosmonauta
```

If I try a simple blank commit I've a failure on "Deploy theme" action, these are error logs:

```
2020-03-17T18:38:35.2938186Z Error: Request failed with status code 413
2020-03-17T18:38:35.2963057Z     at createError (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.2.0/dist/index.js:646:15)
2020-03-17T18:38:35.2971497Z     at settle (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.2.0/dist/index.js:8063:12)
2020-03-17T18:38:35.2972347Z     at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.2.0/dist/index.js:9093:11)
2020-03-17T18:38:35.2972950Z     at IncomingMessage.emit (events.js:215:7)
2020-03-17T18:38:35.2977539Z     at endReadableNT (_stream_readable.js:1184:12)
2020-03-17T18:38:35.2978939Z     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2020-03-17T18:38:35.2979881Z   isAxiosError: true,
2020-03-17T18:38:35.2980807Z   toJSON: [Function]
2020-03-17T18:38:35.2981672Z }
2020-03-17T18:38:35.3235437Z Post job cleanup.
```
Thanks!

**Comment by jloh** [comment]
Hey @arrubiu! `413` is a HTTP status code saying that your [payload is too large](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413). Basically saying what you're trying to upload is to big.

Any idea how big your theme is zipped? Anything you can pull out of it to make it a bit smaller?

**Comment by vikaspotluri123** [comment]
@arrubiu can you try bumping the version that's used to 1.2.1 (`TryGhost/action-deploy-theme@v1.2.1`)? The issue you're seeing _should_ be fixed by that

**Comment by arrubiu** [comment]
I've tryed with TryGhost/action-deploy-theme@master but I've the same error.

The zip file, removing .git and .github directories, is 1.1M

**Comment by arrubiu** [comment]
I've the same problem if I try to upload the theme directly from the admin panel (1.1M).
It could be a docker problem..

**Comment by arrubiu** [comment]
Ok, solved, the problem was my proxy :)
