### ISSUE TITLE
503 error on deploying theme

### ISSUE THREAD

**Issue by mmatur** [TryGhost/action-deploy-theme#13]
### Description

I am using github action to deploy my ghost theme into Ghost Pro. 

I have 502 error when uploading the theme.

```
Error: Request failed with status code 503
    at createError (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.2.1/dist/index.js:956:15)
    at settle (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.2.1/dist/index.js:8437:12)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.2.1/dist/index.js:9466:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  isAxiosError: true,
  toJSON: [Function]
```

But the theme is present in the UI

![image](https://user-images.githubusercontent.com/1776972/77173921-9425ed00-6ac0-11ea-9a49-9ec4332b888d.png)

**Comment by ErisDS** [comment]
Hi there!  This is not a bug with the action. If you're having any issue with a **Ghost(Pro)** site, please drop us an email on support@ghost.org and we'll be more than happy to give you a hand directly 🙂
