### ISSUE TITLE
Action Deploy Error

### ISSUE THREAD

**Issue by cuongtqtran** [TryGhost/action-deploy-theme#41]
I faced the issue with deploy as below
```
Run TryGhost/action-deploy-theme@v1.4.1
Error: Request failed with status code 503
/usr/bin/zip -r ubud.zip . -x *.git* *.zip yarn* npm* node_modules* *routes.yaml *redirects.yaml *redirects.json
    at createError (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.1/dist/index.js:975:15)
  adding: home-image-circle.hbs (deflated 58%)
    at settle (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.1/dist/index.js:8530:12)
  adding: partials/ (stored 0%)
    at IncomingMessage.handleStreamEnd (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.1/dist/index.js:9559:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  isAxiosError: true,
  toJSON: [Function]
}
```

**Comment by ErisDS** [comment]
503 means your site was temporarily unavailable. Ghost shows this whilst restarting. This is a temporary failure & you should retry the build.
