### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by oskarkrawczyk** [TryGhost/action-deploy-theme#43]
Trying version 1.4.1.

```
[...]

  adding: index.hbs (deflated 36%)
70
Error [NotFoundError]: Resource not found
71
    at /home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.1/dist/index.js:7300:33
72
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
73
    at async main (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.1/dist/index.js:1572:9) {
74
  name: 'NotFoundError',
75
  context: null,
76
  type: 'NotFoundError',
77
  details: null,
78
  property: null,
79
  help: null,
80
  code: null,
81
  id: '8a7a8940-acb0-11eb-a1f8-31e5b5a12110'
82
}
```

**Comment by ErisDS** [comment]
This is a 404. Is your url correct?

**Comment by sharmapratik88** [comment]
How was this solved? I'm getting the same issue and have checked the URL is correct.

```
Error: Resource not found
    at /home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.1/dist/index.js:7300:33
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.4.1/dist/index.js:1572:9) {
  name: undefined,
  errorType: 'NotFoundError'
```
