### ISSUE TITLE
Error: Request body larger than maxBodyLength limit

### ISSUE THREAD

**Issue by kaveet** [TryGhost/action-deploy-theme#68]
Hello!

I'm seeing this issue when uploading a ~150MB theme file. I've confirmed that I'm running `@tryghost/admin-api@1.12.0`, which has the patch to increase the `axios` `maxBodyLength` config option to `Infinity` ([patch here](https://github.com/TryGhost/SDK/issues/195)). My Nginx server is configured for a max length of 500MB.

Any ideas?

```shell
Run TryGhost/action-deploy-theme@v1.5.0
  with:
    api-url: ***
    api-key: ***
    theme-name: ***
    file: ./theme.zip
Error [ERR_FR_MAX_BODY_LENGTH_EXCEEDED]: Request body larger than maxBodyLength limit
    at RedirectableRequest.module.exports.549.RedirectableRequest.write (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.5.0/dist/index.js:10098:24)
    at FormData.ondata (internal/streams/legacy.js:19:31)
    at FormData.emit (events.js:314:20)
    at FormData.module.exports.547.CombinedStream.write (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.5.0/dist/index.js:9919:8)
    at DelayedStream.ondata (internal/streams/legacy.js:19:31)
    at DelayedStream.emit (events.js:314:20)
    at DelayedStream.module.exports.152.DelayedStream._handleEmit (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.5.0/dist/index.js:3315:15)
    at ReadStream.source.emit (/home/runner/work/_actions/TryGhost/action-deploy-theme/v1.5.0/dist/index.js:3262:19)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9) {
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by kaveet** [comment]
Update: I've found that the `Infinity` value in the patch above has no effect.

Here's a change I made in a fork to combat this issue (works like a dream!): https://github.com/TryGhost/action-deploy-theme/compare/main...kaveet:main

I'll work on getting this into upstream.

**Comment by ErisDS** [comment]
I think this repo needed a release. Please can you try updating your version in the workflow file to 1.6.0 and let me know if that works?

If it doesn't I will reopen.
